# permissions for end users to view apimatics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apimatic-viewer-role
rules:
- apiGroups:
  - apicodegen.apimatic.io
  resources:
  - apimatics
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apicodegen.apimatic.io
  resources:
  - apimatics/status
  verbs:
  - get
