
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apicodegen.apimatic.io
  resources:
  - apimatics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apicodegen.apimatic.io
  resources:
  - apimatics/finalizers
  verbs:
  - update
- apiGroups:
  - apicodegen.apimatic.io
  resources:
  - apimatics/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - get
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - get
