apiVersion: v1
kind: Namespace
metadata:
  name: apimatic-system
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: apimatic-kubernetes-operator-catalog
  namespace: olm
spec:
  sourceType: grpc
  image: docker.io/apimaticio/apimatic-kubernetes-operator-catalog:v0.0.1
  displayName: APIMatic-Kubernetes-Operator-Catalog
  publisher: APIMatic.io
  updateStrategy:
    registryPoll:
      interval: 10m
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: apimatic-operator-group
  namespace: apimatic-system
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: apimatic-kubernetes-operator-subscription
  namespace: apimatic-system
spec:
  channel: alpha
  name: apimatic-kubernetes-operator
  source: apimatic-kubernetes-operator-catalog
  sourceNamespace: olm
  installPlanApproval: Automatic