apiVersion: apicodegen.apimatic.io/v1beta1
kind: APIMatic
metadata:
  name: apimatic-sample
spec:
  replicas: 3
  podspec:
    apimaticContainerSpec:
      image: 'apimaticio/apimatic-codegen'
      # Create a docker image secret using your username and password that was registered with APIMatic. More information at https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-secret-by-providing-credentials-on-the-command-line
      imagePullSecret: 'apimaticimagesecret'
  servicespec:
    servicetype: 'NodePort'
    apimaticserviceport: 
      nodePort: 32000
      port: 8070
  licensespec:
    licenseSourceType: 'ConfigMap'
    licenseSourceName: 'apimaticlicense'
